### ISSUE TITLE
Additional permissions not working

### ISSUE THREAD

**Issue by xinghul** [jaredhanson/passport-facebook#158]
Setting additional permissions in scope doesn't working for me, here's code:

``` javascript
router.get("/facebook", passport.authenticate("facebook", {
  authType: "reauthenticate",
  scope: ["email", "user_posts"],
  display: "popup"
}));

router.get("/facebook/callback", function (req, res, next) {
  passport.authenticate("facebook", function (err, user) {
    if (err) {
      return res.end(err);      
    }

    req.logIn(user, function (err) {
      if (err) {
        console.log(err);
        res.end(err);
      } else {
        res.redirect("/");
      }
    });
  })(req, res, next);
});
```

Strategy set up:

``` javascript
passport.use(new FacebookStrategy({

      // pull in our app id and secret from our auth.js file
      clientID         : configAuth.facebookAuth.clientID,
      clientSecret     : configAuth.facebookAuth.clientSecret,
      callbackURL      : configAuth.facebookAuth.callbackURL,
      passReqToCallback: true,
      profileFields    : ["id", "emails", "photos", "name"]
    }, function (req, token, refreshToken, profile, done) {

      process.nextTick(function () {
      ......
```

Any ideas?

**Comment by tambling** [comment]
I had this issue, too. I was able to fix it by moving the `scope: [...]` to the options object passed to `new FacebookStrategy`. Pretty sure it has something to do with a recent change to Facebook's OAuth API.

**Comment by rageycomma** [comment]
I know it's been a while, but for me -- this is because the API version supported in this version is old, and because the object that comes back from Facebook, is transformed into another version. 

To get this to work, marginally, I read the source of this module and found there is a limited amount of parameters for profileFields supported:

` var map = {
    'id':          'id',
    'username':    'username',
    'displayName': 'name',
    'name':       ['last_name', 'first_name', 'middle_name'],
    'gender':      'gender',
    'birthday':    'birthday',
    'profileUrl':  'link',
    'emails':      'email',
    'photos':      'picture'
};`

Ensure that on your route, your roles array matches what you have in the profileFields array, and that what you have in the array matches the properties in the object shown above. 

My apologies for resurrecting this old thread, however, this proved to be an issue for me still. If I get time I would like to amend this module to support many more of the supported fields which aren't supported here, for the v2.8 API.
