### ISSUE TITLE
Unclear Functionality - Documentation Request

### ISSUE THREAD

**Issue by netpoetica** [jaredhanson/passport-facebook#39]
I am failing to understand the authorization process, and I have many questions about how this is supposed to work that are probably no-brainers for some people:

After configuring the /login route and the /login/callback route, will all further requests with in my programs always be authenticated? For example, if I call req.isAuthenticated() in the callback for the /login/callback route, I will get TRUE, but if I call req.isAuthetnticated() in arbitrary routes later on, I am not getting TRUE. How do I ensure authentication across routes that are not callbacks?

The access tokens and refresh tokens - how do you get access to them on a per-request basis? Currently, they are parameters only of the /login/callback route. What if I want to have a multitude of RESTful API endpoints all of which need authorization?

Configuring passport.use(function(){ //... }) seems to be simply setting the function that passport.authorize will later reference. What if I don't want to specify a path like /login/callback, but I want to be able to have a different callbackURL each time I authorize (for example, every action the user takes, I want verify they are still authorized, but I don't ALWAYS want to take them back to the initial /login/callback page - I may want to take them to /user/:user_id/project/:project_id).

**Comment by motiazu** [comment]
Thank you, I found the docs very confusing about this and I had to search around for about two hours to make it clear that an api without a website has no reason to use this.

I suggest making the docs more clear about this. While this plugin is responsible for a piece of the puzzle, people who use it don't neccesarly know how the puzzle works and are not only using this library because they don't want to implement it, they also don't know how to do that.
